/**
 * Motif End 2 End Encryption Service API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 2.0.0
 * Contact: info@vipera.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { ConversationIdStatus } from '../model/conversationIdStatus';
import { ErrorVipera } from '../model/errorVipera';
import { HandshakeRequest } from '../model/handshakeRequest';
import { HandshakeResponse } from '../model/handshakeResponse';
import { PublicKeyCertificate } from '../model/publicKeyCertificate';


import { Configuration }                                     from '../configuration';


export interface E2eServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;
    

    /**
    * Get Conversation ID status
    * Get Conversation ID status
    * @param cid ConversationId
    */
    getConversationIdStatus(cid: string, extraHttpRequestParams?: any): Observable<ConversationIdStatus>;

    /**
    * Get E2E Public Key Certificate
    * Get E2E Public Key Certificate
    */
    getPublicKeyCertificate(extraHttpRequestParams?: any): Observable<PublicKeyCertificate>;

    /**
    * Performs an Handshake
    * Performs an Handshake
    * @param handshakeRequest 
    */
    performHandshake(handshakeRequest?: HandshakeRequest, extraHttpRequestParams?: any): Observable<HandshakeResponse>;

}
