/**
 * Motif Context Service API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 2.0.0
 * Contact: info@vipera.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { ErrorVipera } from '../model/errorVipera';
import { ServiceContextAttribute } from '../model/serviceContextAttribute';
import { ServiceContextAttributeCreate } from '../model/serviceContextAttributeCreate';
import { ServiceContextAttributeList } from '../model/serviceContextAttributeList';
import { ServiceContextAttributeUpdate } from '../model/serviceContextAttributeUpdate';


import { Configuration }                                     from '../configuration';


export interface AttributesServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;
    

    /**
    * Creates a Service Context Attribute
    * Creates a Service Context Attribute
    * @param serviceContextAttributeCreate 
    */
    createAttribute(serviceContextAttributeCreate?: ServiceContextAttributeCreate, extraHttpRequestParams?: any): Observable<ServiceContextAttribute>;

    /**
    * Deletes a Service Context Attribute
    * Deletes a Service Context Attribute
    * @param attribute Attribute Name
    */
    deleteAttribute(attribute: string, extraHttpRequestParams?: any): Observable<any>;

    /**
    * Retrieves a Service Context Attribute
    * Retrieves a Service Context Attribute
    * @param attribute Attribute Name
    */
    getAttribute(attribute: string, extraHttpRequestParams?: any): Observable<ServiceContextAttribute>;

    /**
    * Retrieves all Service Context Attributes
    * Retrieves all Service Context Attributes
    */
    getAttributes(extraHttpRequestParams?: any): Observable<ServiceContextAttributeList>;

    /**
    * Updates a Service Context Attribute
    * Updates a Service Context Attribute
    * @param attribute Attribute Name
    * @param serviceContextAttributeUpdate 
    */
    updateAttribute(attribute: string, serviceContextAttributeUpdate?: ServiceContextAttributeUpdate, extraHttpRequestParams?: any): Observable<any>;

}
