/**
 * Motif Auth Access Control Service API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: info@vipera.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { EntitlementResult } from '../model/entitlementResult';
import { ErrorVipera } from '../model/errorVipera';
import { Permission } from '../model/permission';


import { Configuration }                                     from '../configuration';


export interface PermissionsServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;
    

    /**
    * Creates a Permission
    * Creates a Permission
    * @param permission 
    */
    createPermission(permission?: Permission, extraHttpRequestParams?: any): Observable<Permission>;

    /**
    * Deletes a Permission
    * Deletes a Permission
    * @param permissionComponent Component Name
    * @param permissionAction Action (can be CREATE, READ, UPDATE, DELETE or *)
    * @param permissionTarget Method name or *(wildcard)
    */
    deletePermission(permissionComponent: string, permissionAction: string, permissionTarget: string, extraHttpRequestParams?: any): Observable<object>;

    /**
    * Retrieves all current user permissions
    * Retrieves all current user permissions
    */
    getMyselfPermissions(extraHttpRequestParams?: any): Observable<Array<Permission>>;

    /**
    * Retrieves a Permission
    * Retrieves a Permission
    * @param permissionComponent Component Name
    * @param permissionAction Action (can be CREATE, READ, UPDATE, DELETE or *)
    * @param permissionTarget Method name or *(wildcard)
    */
    getPermission(permissionComponent: string, permissionAction: string, permissionTarget: string, extraHttpRequestParams?: any): Observable<Permission>;

    /**
    * Retrieves all permissions
    * Retrieves all permissions
    */
    getPermissions(extraHttpRequestParams?: any): Observable<Array<Permission>>;

    /**
    * Check if permission is assigned to the authenticated user
    * Check if permission is assigned to the authenticated user
    * @param permissionComponent Component Name
    * @param permissionAction Action (can be CREATE, READ, UPDATE, DELETE or *)
    * @param permissionTarget Method name or *(wildcard)
    */
    isMyselfPermissionEntitled(permissionComponent: string, permissionAction: string, permissionTarget: string, extraHttpRequestParams?: any): Observable<EntitlementResult>;

}
