/**
 * Motif License Management Service API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 2.0.0
 * Contact: info@vipera.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { ErrorVipera } from '../model/errorVipera';
import { LicenseList } from '../model/licenseList';


import { Configuration }                                     from '../configuration';


export interface LicenseServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;
    

    /**
    * Deletes license
    * Deletes license
    * @param productName License name
    * @param productVersion 
    */
    deleteLicense(productName: string, productVersion: string, extraHttpRequestParams?: any): Observable<any>;

    /**
    * Returns all licenses
    * Returns all licenses
    */
    listLicenses(extraHttpRequestParams?: any): Observable<LicenseList>;

    /**
    * Uploads license onto server
    * Uploads license onto server
    * @param file 
    */
    uploadLicense(file: Blob, extraHttpRequestParams?: any): Observable<any>;

    /**
    * Validate current Motif version license
    * Validate current Motif version license
    */
    validateLicense(extraHttpRequestParams?: any): Observable<any>;

}
