/**
 * Motif OAuth2 Service API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 2.0.0
 * Contact: info@vipera.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { OAuthToken } from './oAuthToken';


export interface AccessToken extends OAuthToken { 
    /**
     * OAuth2 Refresh Token
     */
    refreshToken: string;
}
