openapi: 3.0.0
info:
  version: 2.0.0
  title: Motif App Content Service API
  contact:
    name: Vipera Plc
    email: info@vipera.com
  license:
    name: Vipera Motif commercial license
    url: 'http://www.vipera.com'
servers:
  - url: 'http://localhost:8080/rest/v2'
    description: Local server
  - url: 'http://ec2-34-209-90-152.us-west-2.compute.amazonaws.com:8080/rest/v2'
    description: Development server
tags:
  - name: engines
    description: Dynamic Engine related
  - name: assets
    description: Asset Bundle related
components:
  securitySchemes:
    vipera_oauth2:
      $ref: './Z_Globals.yaml#/components/securitySchemes/vipera_oauth2'
    vipera_basic:
      $ref: './Z_Globals.yaml#/components/securitySchemes/vipera_basic'
    vipera_cookie:
      $ref: './Z_Globals.yaml#/components/securitySchemes/vipera_cookie'
  schemas: 
    Engine:
      allOf:
        - $ref: '#/components/schemas/EngineCreate' 
        - type: object
          required:
            - domain
          properties:
            domain:
              type: string
              description: ViperaOSGi domain
              example: Default
            created:
              type: string
              example: '2016-08-30 17:12:46.542Z'
              format: 'date-time'
              description: Engine creation timestamp
            lastAppCheck:
              type: string
              example: '2017-09-14 12:16:26.832Z'
              format: 'date-time'  
              description: Last Engine check request timestamp       
          
    EngineCreate:
      type: object
      required:
        - name
        - latestVersion
      properties:
        name:
          description: Engine name
          type: string
          example: EngineName
        latestVersion:
          description: Engine latest version
          type: string
          example: 1.0.1
        forbiddenVersion:
          description: Forbidden versions
          type: string
          example: 1.0.0
        downloadUrl:
          description: Download URL
          type: string
          example: www.google.com/1.0.1

    EngineUpdate:
      type: object
      required:
        - latestVersion
      properties:
        latestVersion:
          description: Engine latest version
          type: string
          example: 1.0.1
        forbiddenVersion:
          description: Forbidden versions
          type: string
          example: 1.0.0
        downloadUrl:
          description: Download URL
          type: string
          example: www.google.com/1.0.1
                        
    AppCheckRequest:
      type: object
      required:
        - engineVer
        - asset
      properties:
        engineVer:
          description: Engine version
          type: string
          example: 1.0.1
        asset:
          description: Asset bundle name
          type: string
          example: AssetName
        assetVer:
          description: Asset bundle version
          type: string
          example: 1.0.1
        userId:
          description: User ID of requestor
          type: string
          example: User Id
        app:
          description: Application Name
          type: string
          example: vipera
        viperaSerial:
          description: Vipera-Serial generated by mobile app
          type: string
          example: r4lWyU4QfZBgNx6F
        devModel:
          description: Device model
          type: string
      
    AppCheckResponse:
      type: object  
      required:
        - name
        - engineLastVersion
        - engineCurVersion
        - assetLastVersion
        - engineForceUpdate
      properties:
        name:
          type: string
          example: engineName
          description: Engine Name
        engineLastVersion:
          description: Engine last version
          type: string
          example: 1.0.1
        engineCurVersion:
          description: Engine current version
          type: string
          example: 1.0.0
        assetLastVersion:
          description: Asset last version
          type: string
          example: 1.0.1
        viperaSerial:
          description: Vipera-Serial for the app instance
          type: string
          example: r4lWyU4QfZBgNx6F
        downloadUrl:
          description: Download URL
          type: string
          example: www.google.com/1.0.1 
        engineForceUpdate:
          description: Send the hint to client to force engine update
          type: boolean
          example: true 
          
    AssetBundleUpload:
      type: object
      required:
        - file
      properties:
        file:
          type: string
          format: binary
          description: Asset bundle in ZIP format
        overwrite:
          type: boolean
          example: false
          description: Whether to overwrite any existing bundle with same domain, name and version
        publish:
          type: boolean
          example: false
          description: Whether to publish the bundle immediately
    AssetBundleEntityList:
      type: array
      items:
          $ref: '#/components/schemas/AssetBundleEntity' 
          
    AssetBundleEntity:
      allOf:
        - $ref: '#/components/schemas/AssetBundleUpdate' 
        - type: object
          required:
            - name
            - domain
            - version
          properties:
            name:
              type: string
              example: assetBundleName
              description: Asset Bundle Name
            domain:
              type: string
              description: ViperaOSGi domain
              example: Default
            version:
              description: Asset Bundle version
              type: string
              example: 1.0.1
            created:
              type: string
              example: '2016-08-30 17:12:46.542Z'
              format: 'date-time'
              description: Asset Bundle creation timestamp
            lastAppCheck:
              type: string
              example: '2017-09-14 12:16:26.832Z'
              format: 'date-time'  
              description: Last App check request timestamp       
            zipData:
              type: string
              format: base64
              description: Original bundle ZIP data    
            zipFileName:
              type: string
              description: Original bundle ZIP file name
              example: FileName
            requiredAppVer:
              type: string
              description: Bundle requires this app version
              example: 1.1.0
              
    AssetBundleUpdate:
      type: object
      required:
        - published
      properties:       
        published:
          description: Whether this bundle is publicly visible
          type: boolean
          example: true
    ApplicationVersion:
      type: object
      required:
            - name
            - domain
            - version
      properties:
            name:
              type: string
              example: applicationVersionName
              description: Application Version Name
            domain:
              type: string
              description: ViperaOSGi domain
              example: Default
            version:
              description: Version
              type: string
              example: 1.0.1
            lastUsage:
              type: string
              example: '2016-08-30 17:12:46.542Z'
              format: 'date-time'
              description: When this instance was last used      
  
  parameters:
    assetPathParam:
      name: asset
      in: path
      required: true
      description: Asset Name
      schema:
        type: string
        example: MyAsset          
    enginePathParam:
      name: engine
      in: path
      required: true
      description: Engine Name
      schema:
        type: string
        example: MyEngine    
    versionPathParam:
      name: version
      in: path
      required: true
      description: Version
      schema:
        type: string
        example: 1.0.0           
    appPathParam:
      name: app
      in: path
      required: true
      description: App Name
      schema:
        type: string
        example: MyApp          
paths:
  /appcont/domains/{domain}/engines:
    post:
      operationId: createEngine
      tags:
        - engines
      description: Registers a new dynamic engine configuration
      summary: Registers a new dynamic engine configuration
      security:
        - vipera_oauth2:
          - 'all:all'
        - vipera_basic: []
        - vipera_cookie: []
      parameters:
        - $ref: './Z_Globals.yaml#/components/parameters/domainPathParam'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/EngineCreate'  
      responses:
        '201':
          description: The engine created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Engine'
        default:
          $ref: './Z_Globals.yaml#/components/responses/GeneralViperaError'  
    get:
      operationId: getEngines
      tags:
        - engines
      description: Looks up all dynamic engine configurations for a given domain
      summary: Looks up all dynamic engine configurations for a given domain
      security:
        - vipera_oauth2:
          - 'all:all'
        - vipera_basic: []
        - vipera_cookie: []
      parameters:
        - $ref: './Z_Globals.yaml#/components/parameters/domainPathParam'
      responses:
        '200':
          description: Returns the list of engines of this domain
          content:
            application/json:
              schema:
                type: array
                items:
                    $ref: '#/components/schemas/Engine' 
        default:
          $ref: './Z_Globals.yaml#/components/responses/GeneralViperaError'

  /appcont/domains/{domain}/engines/{engine}:
    get:
      operationId: getEngine
      tags:
        - engines
      description: Looks up a dynamic engine configuration
      summary: Looks up a dynamic engine configuration
      security:
        - vipera_oauth2:
          - 'all:all'
        - vipera_basic: []
        - vipera_cookie: []
      parameters:
        - $ref: './Z_Globals.yaml#/components/parameters/domainPathParam'
        - $ref: '#/components/parameters/enginePathParam'
      responses:
        '200':
          description: Return the engine we are looking for
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Engine'
        default:
          $ref: './Z_Globals.yaml#/components/responses/GeneralViperaError'
    put:
      operationId: updateEngine
      tags:
        - engines
      description: Updates a registered dynamic engine configuration
      summary: Updates a registered dynamic engine configuration
      security:
        - vipera_oauth2:
          - 'all:all'
        - vipera_basic: []
        - vipera_cookie: []
      parameters:
        - $ref: './Z_Globals.yaml#/components/parameters/domainPathParam'
        - $ref: '#/components/parameters/enginePathParam'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/EngineUpdate'  
      responses:
        '204':
          $ref: './Z_Globals.yaml#/components/responses/GeneralViperaOkResponse' 
        default:
          $ref: './Z_Globals.yaml#/components/responses/GeneralViperaError' 
    delete:
      operationId: deleteEngine
      tags:
        - engines
      description: Deletes a dynamic engine configuration
      summary: Deletes a dynamic engine configuration
      security:
        - vipera_oauth2:
          - 'all:all'
        - vipera_basic: []
        - vipera_cookie: []
      parameters:
        - $ref: './Z_Globals.yaml#/components/parameters/domainPathParam'
        - $ref: '#/components/parameters/enginePathParam'
      responses:
        '204':
          $ref: './Z_Globals.yaml#/components/responses/GeneralViperaOkResponse'
        default:
          $ref: './Z_Globals.yaml#/components/responses/GeneralViperaError'

  /appcont/domains/{domain}/engines/tracking/versions:
    get:
      operationId: getTrackedEnginesVersions
      tags:
        - engines
      description: Lists all tracked engines versions
      summary: Lists all tracked engines versions
      security:
        - vipera_oauth2:
          - 'all:all'
        - vipera_basic: []
        - vipera_cookie: []
      parameters:
        - $ref: './Z_Globals.yaml#/components/parameters/domainPathParam'
      responses:
        '200':
          description: Returns a list of the versions of the different engines
          content:
            application/json:
              schema:
                type: array
                items:
                    $ref: '#/components/schemas/ApplicationVersion' 
        default:
          $ref: './Z_Globals.yaml#/components/responses/GeneralViperaError'
    delete:
      operationId: deleteTrackedEnginesVersions
      tags:
        - engines
      description: Deletes all tracked engines versions
      summary: Deletes all tracked engines versions
      security:
        - vipera_oauth2:
          - 'all:all'
        - vipera_basic: []
        - vipera_cookie: []
      parameters:
        - $ref: './Z_Globals.yaml#/components/parameters/domainPathParam'
      responses:
        '204':
          $ref: './Z_Globals.yaml#/components/responses/GeneralViperaOkResponse'
        default:
          $ref: './Z_Globals.yaml#/components/responses/GeneralViperaError'
  
  /appcont/domains/{domain}/engines/{engine}/tracking/versions:
    get:
      operationId: getTrackedEngineVersions
      tags:
        - engines
      description: Retrieve tracked engine versions
      summary: Retrieve tracked engine versions
      security:
        - vipera_oauth2:
          - 'all:all'
        - vipera_basic: []
        - vipera_cookie: []
      parameters:
        - $ref: './Z_Globals.yaml#/components/parameters/domainPathParam'
        - $ref: '#/components/parameters/enginePathParam'
      responses:
        '200':
          description: Returns the versions of the engine required
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string
        default:
          $ref: './Z_Globals.yaml#/components/responses/GeneralViperaError'

  /appcont/domains/{domain}/engines/{engine}/check:
    post:
      operationId: checkEngine
      tags:
        - engines
      description: Dynamic engine version check 
      summary: Dynamic engine version check
      security:
        - vipera_oauth2:
          - 'all:all'
        - vipera_basic: []
        - vipera_cookie: []
      parameters:
        - $ref: './Z_Globals.yaml#/components/parameters/domainPathParam'
        - $ref: '#/components/parameters/enginePathParam'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AppCheckRequest'  
      responses:
        '200':
          description: Returns the information of the dynamic engine
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AppCheckResponse'
        default:
          $ref: './Z_Globals.yaml#/components/responses/GeneralViperaError'
          
  /appcont/domains/{domain}/assets:
    put:
      operationId: uploadAsset
      tags:
        - assets
      description: Uploads an asset bundle to the server DB 
      summary: Uploads an asset bundle to the server DB
      security:
        - vipera_oauth2:
          - 'all:all'
        - vipera_basic: []
        - vipera_cookie: []
      parameters:
        - $ref: './Z_Globals.yaml#/components/parameters/domainPathParam'
      requestBody:
        content:
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/AssetBundleUpload'  
      responses:
        '204':
          $ref: './Z_Globals.yaml#/components/responses/GeneralViperaOkResponse'
        default:
          $ref: './Z_Globals.yaml#/components/responses/GeneralViperaError'
    get:
      operationId: getAssets
      tags:
        - assets
      description: Retrieves asset bundles by domain
      summary: Retrieves asset bundles by domain
      security:
        - vipera_oauth2:
          - 'all:all'
        - vipera_basic: []
        - vipera_cookie: []
      parameters:
        - $ref: './Z_Globals.yaml#/components/parameters/domainPathParam'
      responses:
        '200':
          description: Returns the asset bundles
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AssetBundleEntityList'
        default:
          $ref: './Z_Globals.yaml#/components/responses/GeneralViperaError'
 
  /appcont/domains/{domain}/assets/{asset}/versions/{version}:
    put:
      operationId: updateAsset
      tags:
        - assets
      description: Updates the public flag of an asset bundle
      summary: Updates the public flag of an asset bundle
      security:
        - vipera_oauth2:
          - 'all:all'
        - vipera_basic: []
        - vipera_cookie: []
      parameters:
        - $ref: './Z_Globals.yaml#/components/parameters/domainPathParam'
        - $ref: '#/components/parameters/assetPathParam'
        - $ref: '#/components/parameters/versionPathParam'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AssetBundleUpdate'
      responses:
        '204':
          $ref: './Z_Globals.yaml#/components/responses/GeneralViperaOkResponse'
        default:
          $ref: './Z_Globals.yaml#/components/responses/GeneralViperaError'
    get:
      operationId: downloadAsset
      tags:
        - assets
      description: Downloads an asset bundle from the DB
      summary: Downloads an asset bundle from the DB
      security:
        - vipera_oauth2:
          - 'all:all'
        - vipera_basic: []
        - vipera_cookie: []
      parameters:
        - $ref: './Z_Globals.yaml#/components/parameters/domainPathParam'
        - $ref: '#/components/parameters/assetPathParam'
        - $ref: '#/components/parameters/versionPathParam'
      responses:
        '200':
          description: Te asset in a zip format
          content:
            application/zip:
              schema:
                type: string
                format: binary
        default:
          $ref: './Z_Globals.yaml#/components/responses/GeneralViperaError'
    delete:
      operationId: deleteAsset
      tags:
        - assets
      description: Deletes a version of a bundle
      summary: Deletes a version of a bundle
      security:
        - vipera_oauth2:
          - 'all:all'
        - vipera_basic: []
        - vipera_cookie: []
      parameters:
        - $ref: './Z_Globals.yaml#/components/parameters/domainPathParam'
        - $ref: '#/components/parameters/assetPathParam'
        - $ref: '#/components/parameters/versionPathParam'
      responses:
        '204':
          $ref: './Z_Globals.yaml#/components/responses/GeneralViperaOkResponse'
        default:
          $ref: './Z_Globals.yaml#/components/responses/GeneralViperaError'
