openapi: 3.0.0
info:
  version: 2.0.0
  title: Motif Configuration Service API
  contact:
    name: Vipera Plc
    email: info@vipera.com
  license:
    name: Vipera Motif commercial license
    url: 'http://www.vipera.com'
servers:
  - url: 'http://localhost:8080/rest/v2'
tags:
  - name: configurations
    description: Configurations related
  - name: settings
    description: Settings related
components:
  securitySchemes:
    vipera_oauth2:
      $ref: './Z_Globals.yaml#/components/securitySchemes/vipera_oauth2'
    vipera_basic:
      $ref: './Z_Globals.yaml#/components/securitySchemes/vipera_basic'
    vipera_cookie:
      $ref: './Z_Globals.yaml#/components/securitySchemes/vipera_cookie'
  schemas: 
    ConfigurationUpload:
      type: object
      required:
        - file
      properties:
        file:
          type: string
          format: binary
        force:
          type: boolean
          example: false

    Service:
      type: object
      required:
        - name
      properties:
        name:
          type: string
          example: TestService  
          
    ServiceList:
      type: array
      items:
          $ref: '#/components/schemas/Service'
    
    SettingList:
      type: array
      items:
          $ref: '#/components/schemas/SettingEntity' 
          
    SettingEntity:
      type: object
      allOf:
       - $ref: '#/components/schemas/Setting' 
       - type: object
         required:
          - serviceId
          - name
         properties:
          name:
            type: string
            example: MySetting
          serviceId:
            type: string
            example: com.vipera.osgi.foundation.webcontent  
          tag:
            type: string
            example : v2       
          lastMod:
                  type: string
                  example: '2016-08-30 17:12:46.542Z'
                  format: 'date-time'
                
    Setting:
      type: object
      required:
        - dynamic
        - crypted
      properties:
        value:
          type: string
          example: testValue  
        type:
          type: string
          example: java.lang.String  
        dynamic:
          type: boolean
          example : true
          description: 'true if when changed does not requires server restart'
        crypted:
          type: boolean
          example : true
          description: 'true if contains sensitive values such as passwords'

    SettingUpdate:
      type: object
      allOf:
        - $ref: '#/components/schemas/Setting'
              
    SettingCreate:
      type: object
      allOf:
        - $ref: '#/components/schemas/Setting'
        - type: object
          required:
            - name
          properties:
            name:
              type: string
              example: testSetting  

    Tag:
      type: object
      required:
        - tag
      properties:
        tag:
          type: string
          example: TestTag  
          
    TagList:
      type: array
      items:
          $ref: '#/components/schemas/Tag'
          
  parameters:
    tagPathParam:
      name: tag
      description: Filter param. Not mandatory      
      in: path
      required: true
      schema:
        type: string
        example: 'v2'           
    servicePathParam:
      name: service
      in: path
      required: true
      schema:
        type: string
        example: 'com.vipera.osgi.foundation.webcontent'
    settingPathParam:
      name: setting
      in: path
      required: true
      schema:
        type: string
        example: 'MySetting'
    propertyPathParam:
      name: property
      in: path
      required: true
      schema:
        type: string
        example: 'MySetting'
paths:
  /cfg/configurations/xml:
    put:
      operationId: uploadXml
      tags:
        - configurations
      description: Uploads XML configuration file
      summary: Uploads XML configuration file
      security:
        - vipera_oauth2:
          - 'all:all'
        - vipera_basic: []
        - vipera_cookie: []
      requestBody:
        content:
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/ConfigurationUpload'
      responses:
        '204':
          $ref: './Z_Globals.yaml#/components/responses/GeneralViperaOkResponse'
        default:
          $ref: './Z_Globals.yaml#/components/responses/GeneralViperaError'
    get:
      operationId: downloadXml
      tags:
        - configurations
      description: Downloads XML configuration file
      summary: Downloads XML configuration file
      security:
        - vipera_oauth2:
          - 'all:all'
        - vipera_basic: []
        - vipera_cookie: []  
      responses:
        '200':
          description: OK
          content:
            application/zip:
              schema:
                type: string
                format: binary
        default:
          $ref: './Z_Globals.yaml#/components/responses/GeneralViperaError'
  
  /cfg/configurations/tags/{tag}/xml:
    get:
      operationId: downloadXmlTaggedSettings
      tags:
        - configurations
      description: Downloads XML configuration file with tagged properties
      summary: Downloads XML configuration file with tagged properties
      security:
        - vipera_oauth2:
          - 'all:all'
        - vipera_basic: []
        - vipera_cookie: []
      parameters:
        - $ref: '#/components/parameters/tagPathParam'   
      responses:
        '200':
          description: OK
          content:
            application/zip:
              schema:
                type: string
                format: binary
        default:
          $ref: './Z_Globals.yaml#/components/responses/GeneralViperaError'

  /cfg/settings/services:
    get:
      operationId: getServices
      tags:
        - settings
      description: Retrieves Configurable Services
      summary: Retrieves Configurable Services
      security:
        - vipera_oauth2:
          - 'all:all'
        - vipera_basic: []
        - vipera_cookie: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ServiceList'
        default:
          $ref: './Z_Globals.yaml#/components/responses/GeneralViperaError'

  /cfg/settings/services/{service}:
    get:
      operationId: getSettings
      tags:
        - settings
      description: Retrieves Configuration Settings
      summary: Retrieves Configuration Settings
      security:
        - vipera_oauth2:
          - 'all:all'
        - vipera_basic: []
        - vipera_cookie: []
      parameters:
        - $ref: '#/components/parameters/servicePathParam'   
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SettingList'
        default:
          $ref: './Z_Globals.yaml#/components/responses/GeneralViperaError'
    delete:
      operationId: DeleteSettings
      tags:
        - settings
      description: Deletes all current properties for a service.
      summary: Deletes all current properties for a service.
      security:
        - vipera_oauth2:
          - 'all:all'
        - vipera_basic: []
        - vipera_cookie: []
      parameters:
        - $ref: '#/components/parameters/servicePathParam' 
      responses:
        '204':
          $ref: './Z_Globals.yaml#/components/responses/GeneralViperaOkResponse'      
        default:
          $ref: './Z_Globals.yaml#/components/responses/GeneralViperaError'
 
  /cfg/settings/services/{service}/settings:
    post:
      operationId: createSetting
      tags:
        - settings
      description: Creates Configuration Setting
      summary: Creates Configuration Setting
      security:
        - vipera_oauth2:
          - 'all:all'
        - vipera_basic: []
        - vipera_cookie: []
      parameters:
        - $ref: '#/components/parameters/servicePathParam'   
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SettingCreate'  
      responses:
        '201':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SettingEntity'
        default:
          $ref: './Z_Globals.yaml#/components/responses/GeneralViperaError'

  /cfg/settings/services/{service}/settings/{setting}:
    get:
      operationId: getSetting
      tags:
        - settings
      description: Retrieves Configuration Setting
      summary: Retrieves Configuration Setting
      security:
        - vipera_oauth2:
          - 'all:all'
        - vipera_basic: []
        - vipera_cookie: []
      parameters:
        - $ref: '#/components/parameters/servicePathParam'   
        - $ref: '#/components/parameters/settingPathParam'  
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SettingEntity'
        default:
          $ref: './Z_Globals.yaml#/components/responses/GeneralViperaError'
   
    put:
      operationId: updateSetting
      tags:
        - settings
      description: Updates Configuration Setting
      summary: Updates Configuration Setting
      security:
        - vipera_oauth2:
          - 'all:all'
        - vipera_basic: []
        - vipera_cookie: []
      parameters:
        - $ref: '#/components/parameters/servicePathParam'   
        - $ref: '#/components/parameters/settingPathParam'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SettingUpdate'  
      responses:
        '204':
          $ref: './Z_Globals.yaml#/components/responses/GeneralViperaOkResponse'
        default:
          $ref: './Z_Globals.yaml#/components/responses/GeneralViperaError'
    delete:
      operationId: DeleteSetting
      tags:
        - settings
      description: Deletes a current property for a service
      summary: Deletes a current property for a service
      security:
        - vipera_oauth2:
          - 'all:all'
        - vipera_basic: []
        - vipera_cookie: []
      parameters:
        - $ref: '#/components/parameters/servicePathParam'   
        - $ref: '#/components/parameters/settingPathParam' 
      responses:
        '204':
          $ref: './Z_Globals.yaml#/components/responses/GeneralViperaOkResponse'      
        default:
          $ref: './Z_Globals.yaml#/components/responses/GeneralViperaError'
           
  /cfg/configurations/tags/{tag}/restore:
    post:
      operationId: tagRestore
      tags:
        - configurations
      description: Restores a version tag. All properties bearing the specified tag will become the active ones.
      summary: Restores a version tag
      security:
        - vipera_oauth2:
          - 'all:all'
        - vipera_basic: []
        - vipera_cookie: []
      parameters:
        - $ref: '#/components/parameters/tagPathParam'  
      responses:
        '204':
          $ref: './Z_Globals.yaml#/components/responses/GeneralViperaOkResponse'      
        default:
          $ref: './Z_Globals.yaml#/components/responses/GeneralViperaError'
   
  /cfg/configurations/tags:
    post:
      operationId: tagSettings
      tags:
        - configurations
      description: Applies a version tag to all properties
      summary: Applies a version tag to all properties
      security:
        - vipera_oauth2:
          - 'all:all'
        - vipera_basic: []
        - vipera_cookie: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Tag'  
      responses:
        '204':
          $ref: './Z_Globals.yaml#/components/responses/GeneralViperaOkResponse'      
        default:
          $ref: './Z_Globals.yaml#/components/responses/GeneralViperaError' 

    get:
      operationId: getTags
      tags:
        - configurations
      description: Retrieves Available Tags
      summary: Retrieves Available Tags
      security:
        - vipera_oauth2:
          - 'all:all'
        - vipera_basic: []
        - vipera_cookie: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TagList'
        default:
          $ref: './Z_Globals.yaml#/components/responses/GeneralViperaError'
 
  /cfg/configurations/tags/{tag}:
    delete:
      operationId: DeleteTag
      tags:
        - configurations
      description: Deletes Configuration with specified tag
      summary: Deletes Configuration with specified tag
      security:
        - vipera_oauth2:
          - 'all:all'
        - vipera_basic: []
        - vipera_cookie: []
      parameters:
        - $ref: '#/components/parameters/tagPathParam' 
      responses:
        '204':
          $ref: './Z_Globals.yaml#/components/responses/GeneralViperaOkResponse'      
        default:
          $ref: './Z_Globals.yaml#/components/responses/GeneralViperaError'
  
  /cfg/configurations/tags/{tag}/service/{service}:
    post:
      operationId: tagService
      tags:
        - configurations
      description: Applies a version tag to all properties identified by service
      summary: Applies a version tag to all properties identified by service
      security:
        - vipera_oauth2:
          - 'all:all'
        - vipera_basic: []
        - vipera_cookie: []
      parameters:
        - $ref: '#/components/parameters/servicePathParam' 
        - $ref: '#/components/parameters/tagPathParam' 
      responses:
        '204':
          $ref: './Z_Globals.yaml#/components/responses/GeneralViperaOkResponse'      
        default:
          $ref: './Z_Globals.yaml#/components/responses/GeneralViperaError'
  /cfg/configurations/tags/{tag}/service/{service}/property/{property}:
    post:
      operationId: tagSetting
      tags:
        - configurations
      description: Applies a version tag to single property
      summary: Applies a version tag to single property
      security:
        - vipera_oauth2:
          - 'all:all'
        - vipera_basic: []
        - vipera_cookie: []
      parameters:
        - $ref: '#/components/parameters/servicePathParam'   
        - $ref: '#/components/parameters/propertyPathParam'
        - $ref: '#/components/parameters/tagPathParam'    
      responses:
        '204':
          $ref: './Z_Globals.yaml#/components/responses/GeneralViperaOkResponse'      
        default:
          $ref: './Z_Globals.yaml#/components/responses/GeneralViperaError'
 