openapi: 3.0.0
info:
  version: 2.0.0
  title: REST Context Service API
  contact:
    name: Vipera Plc
    email: info@vipera.com
  license:
    name: Vipera Motif commercial license
    url: 'http://www.vipera.com'
servers:
  - url: 'http://localhost:8080/rest/v2'
    description: Local server
  - url: 'http://ec2-34-209-90-152.us-west-2.compute.amazonaws.com:8080/rest/v2'
    description: Development server
tags:
  - name: contexts
    description: REST context related
components:
  
  schemas:
    RestContextCreate:
      type: object
      properties:
        context:
          type: string
          example: 'testContext'
        url:
          type: string
          example: '/testpath'
    RestContextUpdate:
      type: object
      properties:
        url:
          type: string
          example: '/testpath'
  parameters:
    contextNamePathParam:
      name: contextName
      in: path
      required: true
      schema:
        type: string
        example: 'openapi'
paths:
  /restctx/domains/{domain}/applications/{application}/contexts:
    post:
      operationId: createContext
      tags:
        - contexts
      description: Creates a REST Context
      summary: Creates a REST Context
      security:
        - vipera_oauth2:
          - 'all:all'
        - vipera_basic: []
        - vipera_cookie: []
      parameters:
        - $ref: './Z_Globals.yaml#/components/parameters/domainPathParam'
        - $ref: './Z_Globals.yaml#/components/parameters/applicationPathParam'             
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RestContextCreate'
      responses:
        '201':
          description: OK
          content:
            application/json:
              schema:
                $ref: './Z_Globals.yaml#/components/schemas/ServiceContext'
        default:
          $ref: './Z_Globals.yaml#/components/responses/GeneralViperaError'
    get:
      operationId: getContexts
      tags:
        - contexts
      description: Retrieves REST Contexts list
      summary: Retrieves REST Contexts list
      security:
        - vipera_oauth2:
          - 'all:all'
        - vipera_basic: []
        - vipera_cookie: []
      parameters:
        - $ref: './Z_Globals.yaml#/components/parameters/domainPathParam'
        - $ref: './Z_Globals.yaml#/components/parameters/applicationPathParam'             
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: './Z_Globals.yaml#/components/schemas/ServiceContext'      
        default:
          $ref: './Z_Globals.yaml#/components/responses/GeneralViperaError'

  /restctx/domains/{domain}/applications/{application}/contexts/{contextName}:
    get:
      operationId: getContext
      tags:
        - contexts
      description: Retrieves REST Context
      summary: Retrieves REST Context
      security:
        - vipera_oauth2:
          - 'all:all'
        - vipera_basic: []
        - vipera_cookie: []
      parameters:
        - $ref: './Z_Globals.yaml#/components/parameters/domainPathParam'
        - $ref: './Z_Globals.yaml#/components/parameters/applicationPathParam'             
        - $ref: '#/components/parameters/contextNamePathParam'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: './Z_Globals.yaml#/components/schemas/ServiceContext'
        default:
          $ref: './Z_Globals.yaml#/components/responses/GeneralViperaError'
    put:
      operationId: updateContext
      tags:
        - contexts
      description: Update a REST Context
      summary: Update a REST Context
      security:
        - vipera_oauth2:
          - 'all:all'
        - vipera_basic: []
        - vipera_cookie: []
      parameters:
        - $ref: './Z_Globals.yaml#/components/parameters/domainPathParam'
        - $ref: './Z_Globals.yaml#/components/parameters/applicationPathParam'             
        - $ref: '#/components/parameters/contextNamePathParam'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RestContextUpdate'
      responses:
        '204':
          $ref: './Z_Globals.yaml#/components/responses/GeneralViperaOkResponse'
        default:
          $ref: './Z_Globals.yaml#/components/responses/GeneralViperaError'
    delete:
      operationId: deleteContext
      tags:
        - contexts
      description: Deletes a REST Context
      summary: Deletes a REST Context
      security:
        - vipera_oauth2:
          - 'all:all'
        - vipera_basic: []
        - vipera_cookie: []
      parameters:
        - $ref: './Z_Globals.yaml#/components/parameters/domainPathParam'
        - $ref: './Z_Globals.yaml#/components/parameters/applicationPathParam'             
        - $ref: '#/components/parameters/contextNamePathParam'
      responses:
        '204':
          $ref: './Z_Globals.yaml#/components/responses/GeneralViperaOkResponse'
        default:
          $ref: './Z_Globals.yaml#/components/responses/GeneralViperaError'
