openapi: 3.0.0
info:
  version: 2.0.0
  title: Motif Web Content Service API
  contact:
    name: Vipera Plc
    email: info@vipera.com
  license:
    name: Vipera Motif commercial license
    url: 'http://www.vipera.com'
servers:
  - url: 'http://localhost:8080/rest/v2'
    description: Local server
  - url: 'http://ec2-34-209-90-152.us-west-2.compute.amazonaws.com:8080/rest/v2'
    description: Development server
tags:
  - name: contexts
    description: Web Content context related
  - name: bundles
    description: Web Content bundle related
components:
  
  schemas:
    WebContentContextCreate:
      type: object
      properties:
        context:
          type: string
          example: 'testContext'
        httpPath:
          type: string
          example: '/testpath'
    WebContentContextUpdate:
      type: object
      properties:
        httpPath:
          type: string
          example: '/testpath'
    BundleUpload:
      type: object
      required:
        - bundle
      properties:
        bundle:
          type: string
          format: binary
        overwrite:
          type: boolean
          example: false
    BundleUpdate:
      type: object
      properties:
        context:
          type: string
          example: '/my-console'
        domain:
          type: string
          example: 'Default'
        application:
          type: string
          example: 'vipera'
    BundleStatus:
      type: object
      properties:
        info:
          $ref: '#/components/schemas/Bundle' 
        status:
          type: array
          items:
             $ref: '#/components/schemas/ClusterBundleStatus' 
    ClusterBundleStatus:
      type: object
      properties:
        status:
          type: string
          example: PUBLISHED
        instance:
          type: string
          example: Node1  
    Bundle:
      type: object
      properties:
        name:
          type: string
          example: 'my-console'
        version:
          type: string
          example: '1.0.0'
        context:
          type: string
          example: '/webconsole'
  parameters:
    bundleNamePathParam:
      name: bundleName
      in: path
      required: true
      schema:
        type: string
        example: 'my-console'
    bundleVersionPathParam:
      name: bundleVersion
      in: path
      required: true
      schema:
        type: string
        example: '1.0.0'
    contextNamePathParam:
      name: contextName
      in: path
      required: true
      schema:
        type: string
        example: 'openapi'
paths:
  /webcontent/domains/{domain}/applications/{application}/contexts:
    post:
      operationId: createContext
      tags:
        - contexts
      description: Creates a Web Content Context
      summary: Creates a Web Content Context
      security:
        - vipera_oauth2:
          - 'all:all'
        - vipera_basic: []
        - vipera_cookie: []
      parameters:
        - $ref: './Z_Globals.yaml#/components/parameters/domainPathParam'
        - $ref: './Z_Globals.yaml#/components/parameters/applicationPathParam'             
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/WebContentContextCreate'
      responses:
        '201':
          description: OK
          content:
            application/json:
              schema:
                $ref: './Z_Globals.yaml#/components/schemas/ServiceContext'
        default:
          $ref: './Z_Globals.yaml#/components/responses/GeneralViperaError'
    get:
      operationId: getContexts
      tags:
        - contexts
      description: Retrieves Web Content Contexts list
      summary: Retrieves Web Content Contexts list
      security:
        - vipera_oauth2:
          - 'all:all'
        - vipera_basic: []
        - vipera_cookie: []
      parameters:
        - $ref: './Z_Globals.yaml#/components/parameters/domainPathParam'
        - $ref: './Z_Globals.yaml#/components/parameters/applicationPathParam'             
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: './Z_Globals.yaml#/components/schemas/ServiceContext'      
        default:
          $ref: './Z_Globals.yaml#/components/responses/GeneralViperaError'

  /webcontent/domains/{domain}/applications/{application}/contexts/{contextName}:
    get:
      operationId: getContext
      tags:
        - contexts
      description: Retrieves Web Content Context
      summary: Retrieves Web Content Context
      security:
        - vipera_oauth2:
          - 'all:all'
        - vipera_basic: []
        - vipera_cookie: []
      parameters:
        - $ref: './Z_Globals.yaml#/components/parameters/domainPathParam'
        - $ref: './Z_Globals.yaml#/components/parameters/applicationPathParam'             
        - $ref: '#/components/parameters/contextNamePathParam'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: './Z_Globals.yaml#/components/schemas/ServiceContext'
        default:
          $ref: './Z_Globals.yaml#/components/responses/GeneralViperaError'
    put:
      operationId: updateContext
      tags:
        - contexts
      description: Update a Web Content Context
      summary: Update a Web Content Context
      security:
        - vipera_oauth2:
          - 'all:all'
        - vipera_basic: []
        - vipera_cookie: []
      parameters:
        - $ref: './Z_Globals.yaml#/components/parameters/domainPathParam'
        - $ref: './Z_Globals.yaml#/components/parameters/applicationPathParam'             
        - $ref: '#/components/parameters/contextNamePathParam'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/WebContentContextUpdate'
      responses:
        '204':
          $ref: './Z_Globals.yaml#/components/responses/GeneralViperaOkResponse'
        default:
          $ref: './Z_Globals.yaml#/components/responses/GeneralViperaError'
    delete:
      operationId: deleteContext
      tags:
        - contexts
      description: Deletes a Web Content Context
      summary: Deletes a Web Content Context
      security:
        - vipera_oauth2:
          - 'all:all'
        - vipera_basic: []
        - vipera_cookie: []
      parameters:
        - $ref: './Z_Globals.yaml#/components/parameters/domainPathParam'
        - $ref: './Z_Globals.yaml#/components/parameters/applicationPathParam'             
        - $ref: '#/components/parameters/contextNamePathParam'
      responses:
        '204':
          $ref: './Z_Globals.yaml#/components/responses/GeneralViperaOkResponse'
        default:
          $ref: './Z_Globals.yaml#/components/responses/GeneralViperaError'

  /webcontent/contexts/attributes:
    get:
      operationId: getSupportedAttributes
      tags:
        - contexts
      description: Retrieves Web Content Context supported attributes
      summary: Retrieves Web Content Context supported attributes
      security:
        - vipera_oauth2:
          - 'all:all'
        - vipera_basic: []
        - vipera_cookie: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: './Z_Globals.yaml#/components/schemas/ServiceContextAttribute'      
        default:
          $ref: './Z_Globals.yaml#/components/responses/GeneralViperaError'

  /webcontent/bundles:
    put:
      operationId: uploadBundle
      tags:
        - bundles
      description: Uploads a Web Content Bundle
      summary: Uploads a Web Content Bundle
      security:
        - vipera_oauth2:
          - 'all:all'
        - vipera_basic: []
        - vipera_cookie: []
      requestBody:
        content:
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/BundleUpload'
      responses:
        '204':
          $ref: './Z_Globals.yaml#/components/responses/GeneralViperaOkResponse'
        default:
          $ref: './Z_Globals.yaml#/components/responses/GeneralViperaError'
          
  /webcontent/bundles/info:
    get:
      operationId: getBundlesList
      tags:
        - bundles
      description: Retrieves Web Content Bundles Info
      summary: Retrieves Web Content Bundles Info
      security:
        - vipera_oauth2:
          - 'all:all'
        - vipera_basic: []
        - vipera_cookie: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/BundleStatus' 
        default:
          $ref: './Z_Globals.yaml#/components/responses/GeneralViperaError'

  /webcontent/bundles/{bundleName}/versions/{bundleVersion}:
    get:
      operationId: downloadBundle
      tags:
        - bundles
      description: Downloads a Web Content Bundle
      summary: Downloads a Web Content Bundle
      security:
        - vipera_oauth2:
          - 'all:all'
        - vipera_basic: []
        - vipera_cookie: []
      parameters:
        - $ref: '#/components/parameters/bundleNamePathParam'
        - $ref: '#/components/parameters/bundleVersionPathParam'
      responses:
        '200':
          description: OK
          content:
            application/zip:
              schema:
                type: string
                format: binary
        default:
          $ref: './Z_Globals.yaml#/components/responses/GeneralViperaError'
    put:
      operationId: updateBundle
      tags:
        - bundles
      description: Update a Web Content Bundle
      summary: Update a Web Content Bundle
      security:
        - vipera_oauth2:
          - 'all:all'
        - vipera_basic: []
        - vipera_cookie: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/BundleUpdate'
      parameters:
        - $ref: '#/components/parameters/bundleNamePathParam'
        - $ref: '#/components/parameters/bundleVersionPathParam'
      responses:
        '204':
          $ref: './Z_Globals.yaml#/components/responses/GeneralViperaOkResponse'
        default:
          $ref: './Z_Globals.yaml#/components/responses/GeneralViperaError'
    delete:
      operationId: deleteBundle
      tags:
        - bundles
      description: Delete a Web Content Bundle
      summary: Delete a Web Content Bundle
      security:
        - vipera_oauth2:
          - 'all:all'
        - vipera_basic: []
        - vipera_cookie: []
      parameters:
        - $ref: '#/components/parameters/bundleNamePathParam'
        - $ref: '#/components/parameters/bundleVersionPathParam'
      responses:
        '204':
          $ref: './Z_Globals.yaml#/components/responses/GeneralViperaOkResponse'
        default:
          $ref: './Z_Globals.yaml#/components/responses/GeneralViperaError'

  /webcontent/bundles/{bundleName}/versions/{bundleVersion}/info:
    get:
      operationId: getBundle
      tags:
        - bundles
      description: Retrieves a Web Content Bundle Info
      summary: Retrieves a Web Content Bundle Info
      security:
        - vipera_oauth2:
          - 'all:all'
        - vipera_basic: []
        - vipera_cookie: []
      parameters:
        - $ref: '#/components/parameters/bundleNamePathParam'
        - $ref: '#/components/parameters/bundleVersionPathParam'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BundleStatus'
        default:
          $ref: './Z_Globals.yaml#/components/responses/GeneralViperaError'

  /webcontent/bundles/{bundleName}/versions/{bundleVersion}/publish:
    post:
      operationId: publishBundle
      tags:
        - bundles
      description: Publish a Web Content Bundle
      summary: Publish a Web Content Bundle
      security:
        - vipera_oauth2:
          - 'all:all'
        - vipera_basic: []
        - vipera_cookie: []
      parameters:
        - $ref: '#/components/parameters/bundleNamePathParam'
        - $ref: '#/components/parameters/bundleVersionPathParam'
      responses:
        '204':
          $ref: './Z_Globals.yaml#/components/responses/GeneralViperaOkResponse'
        default:
          $ref: './Z_Globals.yaml#/components/responses/GeneralViperaError'
          
  /webcontent/bundles/{bundleName}/versions/{bundleVersion}/unpublish:
    post:
      operationId: unpublishBundle
      tags:
        - bundles
      description: Unpublish a Web Content Bundle
      summary: Unpublish a Web Content Bundle
      security:
        - vipera_oauth2:
          - 'all:all'
        - vipera_basic: []
        - vipera_cookie: []
      parameters:
        - $ref: '#/components/parameters/bundleNamePathParam'
        - $ref: '#/components/parameters/bundleVersionPathParam'
      responses:
        '204':
          $ref: './Z_Globals.yaml#/components/responses/GeneralViperaOkResponse'
        default:
          $ref: './Z_Globals.yaml#/components/responses/GeneralViperaError'