/**
 * Motif File Install Service API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: info@vipera.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { ErrorVipera } from '../model/errorVipera';
import { OsgiBundle } from '../model/osgiBundle';
import { OsgiBundleDirectory } from '../model/osgiBundleDirectory';


import { Configuration }                                     from '../configuration';


export interface DirectoriesServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;
    

    /**
    * Deletes Bundle Plugin jar contained into directory
    * Deletes Bundle Plugin jar contained into directory
    * @param directory Directory relative path
    * @param bundle Bundle File Name
    */
    deleteBundle(directory: string, bundle: string, extraHttpRequestParams?: any): Observable<object>;

    /**
    * Deletes Bundle Plugin jars included into directory
    * Deletes Bundle Plugin jars included into directory
    * @param directory Directory relative path
    */
    deleteBundles(directory: string, extraHttpRequestParams?: any): Observable<object>;

    /**
    * Lists the OSGi bundles in a directory
    * Lists the OSGi bundles in a directory
    * @param directory Directory relative path
    */
    listBundles(directory: string, extraHttpRequestParams?: any): Observable<Array<OsgiBundle>>;

    /**
    * Lists the OSGi bundle directories
    * Lists the OSGi bundle directories
    */
    listDirectories(extraHttpRequestParams?: any): Observable<Array<OsgiBundleDirectory>>;

    /**
    * Scans a directory and installs/updates/deletes bundles
    * Scans a directory and installs/updates/deletes bundles
    * @param directory Directory relative path
    */
    scanDirectory(directory: string, extraHttpRequestParams?: any): Observable<object>;

}
