/**
 * Motif Datarecords Service API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: info@vipera.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Datarecord } from './datarecord';


export interface DatarecordList { 
    headers?: Array<string>;
    records?: Array<Datarecord>;
}

