/**
 * Motif Security Service API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: info@vipera.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { ErrorVipera } from '../model/errorVipera';
import { Session } from '../model/session';


import { Configuration }                                     from '../configuration';


export interface SessionServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;
    

    /**
    * Check current user session
    * Check current user session
    */
    checkCurrentUserSession(extraHttpRequestParams?: any): Observable<Session>;

    /**
    * Close current user session
    * Close current user session
    */
    closeCurrentUserSession(extraHttpRequestParams?: any): Observable<object>;

    /**
    * Open current user session
    * Open current user session
    */
    openCurrentUserSession(extraHttpRequestParams?: any): Observable<Session>;

}
