openapi: 3.0.0
info:
  version: 2.0.0
  title: Motif Security Service API
  contact:
    name: Vipera Plc
    email: info@vipera.com
  license:
    name: Vipera Motif commercial license
    url: 'http://www.vipera.com'
servers:
  - url: 'http://localhost:8080/rest/v2'
tags:
  - name: security
    description: Security Service
components:
  securitySchemes:
    vipera_oauth2:
      $ref: './Z_Globals.yaml#/components/securitySchemes/vipera_oauth2'
    vipera_basic:
      $ref: './Z_Globals.yaml#/components/securitySchemes/vipera_basic'
    vipera_cookie:
      $ref: './Z_Globals.yaml#/components/securitySchemes/vipera_cookie'
  schemas:           
    Session:
      type: object
      required:
        - id
        - lastAccess
        - secure
        - channel
        - domain
        - application
        - user
        - lastRequestId
        - expiry
        - clientIp
        - shared
      properties:
        id:
          type: string
          description: Session ID
          example: 3h3hgf234gf23hg4f23h4hg23f4h23gf4h2
        lastAccess:
          type: string
          format: 'date-time'
          example: '2016-08-30 17:12:46.542Z'
        secure:
          type: boolean
          description: Whether this session is secure
          example: true
        channel:
          type: string
          description: Channel
          example: JSON
        domain:
          type: string
          description: Domain
          example: Default
        application:
          type: string
          description: Application
          example: Vipera
        user:
          type: string
          description: User
          example: joe
        lastRequestId:
          type: integer
          description: Last request ID
          example: 123
        expiry:
          type: string
          description: Expiry
          example: 5h
        clientIp:
          type: string
          description: Client IP
          example: 8.8.8.8
        shared:
          type: boolean
          description: Whether this session is shared between multiple users
          example: false
  parameters:
    sessionPathParam:
      name: session
      required: true
      in: path
      description: Session
      schema:
        type: string
        example: 3h3hgf234gf23hg4f23h4hg23f4h23gf4h2
    sessionQueryParam:
      name: session
      required: false
      in: query
      description: Session
      schema:
        type: string
        example: 3h3hgf234gf23hg4f23h4hg23f4h23gf4h2
    channelQueryParam:
      name: channel
      required: false
      in: query
      description: Channel
      schema:
        type: string
        example: REST
    domainQueryParam:
      name: domain
      required: false
      in: query
      description: Domain
      schema:
        type: string
        example: Default
    applicationQueryParam:
      name: application
      required: false
      in: query
      description: Application
      schema:
        type: string
        example: Vipera
    clientIpQueryParam:
      name: clientIp
      required: false
      in: query
      description: Client IP
      schema:
        type: string
        example: 10.0.0.1
    userQueryParam:
      name: user
      required: false
      in: query
      description: User
      schema:
        type: string
        example: joe
        
paths:
  /security/sessions:
    get:
      operationId: getSessions
      tags:
        - security
      description: Retrieve open sessions
      summary: Retrieve open sessions
      security:
        - vipera_oauth2:
          - 'all:all'
        - vipera_basic: []
        - vipera_cookie: []
      parameters:
        - $ref: '#/components/parameters/sessionQueryParam'
        - $ref: '#/components/parameters/channelQueryParam'
        - $ref: '#/components/parameters/domainQueryParam'
        - $ref: '#/components/parameters/applicationQueryParam'
        - $ref: '#/components/parameters/clientIpQueryParam'
        - $ref: '#/components/parameters/userQueryParam'
        - $ref: './Z_Globals.yaml#/components/parameters/pageQueryParam'
        - $ref: './Z_Globals.yaml#/components/parameters/pageSizeQueryParam'
      responses:
        '200':
          description: OK
          headers:
            x-page:
              $ref: './Z_Globals.yaml#/components/headers/x-page'
            x-page-size:
              $ref: './Z_Globals.yaml#/components/headers/x-page-size'
            x-total-pages:
              $ref: './Z_Globals.yaml#/components/headers/x-total-pages'
            x-total-records:
              $ref: './Z_Globals.yaml#/components/headers/x-total-records'
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Session'
        default:
          $ref: './Z_Globals.yaml#/components/responses/GeneralViperaError'
  /security/sessions/{session}:
    delete:
      operationId: closeSession
      tags:
        - security
      description: Close session
      summary: Close session
      security:
        - vipera_oauth2:
          - 'all:all'
        - vipera_basic: []
        - vipera_cookie: []
      parameters:
        - $ref: '#/components/parameters/sessionPathParam'
      responses:
        '204':
          $ref: './Z_Globals.yaml#/components/responses/GeneralViperaOkResponse'
        default:
          $ref: './Z_Globals.yaml#/components/responses/GeneralViperaError'          
  /security/sessions/current/logout:
    post:
      operationId: logoutCurrentUser
      tags:
        - security
      description: Logout current user
      summary: Logout current user
      security:
        - vipera_oauth2:
          - 'all:all'
        - vipera_basic: []
        - vipera_cookie: []
      responses:
        '204':
          $ref: './Z_Globals.yaml#/components/responses/GeneralViperaOkResponse'
        default:
          $ref: './Z_Globals.yaml#/components/responses/GeneralViperaError'
  