/**
 * Motif Scheduler Service API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 2.0.0
 * Contact: info@vipera.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ScheduledTaskExecutionEntity { 
    /**
     * Task execution Id
     */
    taskExecId?: string;
    /**
     * Scheduled task that generated this execution
     */
    taskName?: string;
    /**
     * Creation timestamp
     */
    created?: Date;
    /**
     * Elapsed time of this execution (millis)
     */
    elapsed?: number;
    /**
     * Result Code
     */
    resultCode?: string;
    /**
     * esult description
     */
    resultDesc?: string;
    /**
     * Id of the worker instance that actually executed the task
     */
    workerId?: string;
}
