/**
 * Motif Scheduler Service API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: info@vipera.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ScheduledTask } from './scheduledTask';
import { ScheduledTaskEntityAllOf } from './scheduledTaskEntityAllOf';


export interface ScheduledTaskEntity { 
    /**
     * Task enabled or not
     */
    enabled: boolean;
    /**
     * Pattern in cron format to affirm when task must be executed
     */
    cronPattern: string;
    /**
     * Name of the service that exposes the method to call
     */
    serviceName: string;
    /**
     * Method to be called
     */
    serviceMethod: string;
    /**
     * Task parameters in JSON format
     */
    jsonParams?: string;
    /**
     * Cluster execution policy (supported values are JUST_ONE_MEMBER, EVERY_MEMBER)
     */
    clusterExecutionPolicy: string;
    /**
     * Failure policy (supported values are LOG_ONLY, MAIL_OUT)
     */
    failurePolicy: string;
    /**
     * Task Name
     */
    name: string;
    /**
     * Creation timestamp
     */
    created: Date;
    /**
     * Update timestamp
     */
    updated: Date;
}

