/**
 * Motif Platform Service API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 2.0.0
 * Contact: info@vipera.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { Application } from '../model/application';
import { ApplicationCreate } from '../model/applicationCreate';
import { ApplicationUpdate } from '../model/applicationUpdate';
import { ErrorVipera } from '../model/errorVipera';


import { Configuration }                                     from '../configuration';


export interface ApplicationsServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;
    

    /**
    * Creates an application
    * Creates an application
    * @param domain Domain Name
    * @param applicationCreate 
    */
    createApplication(domain: string, applicationCreate?: ApplicationCreate, extraHttpRequestParams?: any): Observable<Application>;

    /**
    * Deletes application
    * Deletes application
    * @param domain Domain Name
    * @param application Application Name
    */
    deleteApplication(domain: string, application: string, extraHttpRequestParams?: any): Observable<any>;

    /**
    * Retrieves application
    * Retrieves application
    * @param domain Domain Name
    * @param application Application Name
    */
    getApplication(domain: string, application: string, extraHttpRequestParams?: any): Observable<Application>;

    /**
    * Retrieves applications
    * Retrieves applications
    * @param domain Domain Name
    */
    getApplications(domain: string, extraHttpRequestParams?: any): Observable<Array<Application>>;

    /**
    * Updates an application
    * Updates an application
    * @param domain Domain Name
    * @param application Application Name
    * @param applicationUpdate 
    */
    updateApplication(domain: string, application: string, applicationUpdate?: ApplicationUpdate, extraHttpRequestParams?: any): Observable<any>;

}
