/**
 * Motif Platform Service API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 2.0.0
 * Contact: info@vipera.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { ErrorVipera } from '../model/errorVipera';
import { Locale } from '../model/locale';
import { LocaleCreate } from '../model/localeCreate';
import { LocaleUpdate } from '../model/localeUpdate';
import { LocalesList } from '../model/localesList';


import { Configuration }                                     from '../configuration';


export interface LocalesServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;
    

    /**
    * Creates a locale
    * Creates a locale
    * @param localeCreate 
    */
    createLocale(localeCreate?: LocaleCreate, extraHttpRequestParams?: any): Observable<Locale>;

    /**
    * Deletes a locale
    * Deletes a locale
    * @param locale Locale Name
    */
    deleteLocale(locale: string, extraHttpRequestParams?: any): Observable<any>;

    /**
    * Retrieves a locale
    * Retrieves a locale
    * @param locale Locale Name
    */
    getLocale(locale: string, extraHttpRequestParams?: any): Observable<Locale>;

    /**
    * Retrieves locales list
    * Retrieves locales list
    */
    getLocalesList(extraHttpRequestParams?: any): Observable<LocalesList>;

    /**
    * Updates a locale
    * Updates a locale
    * @param locale Locale Name
    * @param localeUpdate 
    */
    updateLocale(locale: string, localeUpdate?: LocaleUpdate, extraHttpRequestParams?: any): Observable<any>;

}
