/**
 * Motif Platform Service API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 2.0.0
 * Contact: info@vipera.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
/* tslint:disable:no-unused-variable member-ordering */

import { Inject, Injectable, Optional }                      from '@angular/core';
import { HttpClient, HttpHeaders, HttpParams,
         HttpResponse, HttpEvent }                           from '@angular/common/http';
import { CustomHttpUrlEncodingCodec }                        from '../encoder';

import { Observable }                                        from 'rxjs';

import { ErrorVipera } from '../model/errorVipera';
import { SystemCategory } from '../model/systemCategory';
import { SystemCategoryCreate } from '../model/systemCategoryCreate';
import { SystemMessage } from '../model/systemMessage';
import { SystemMessageCreate } from '../model/systemMessageCreate';
import { SystemMessageUpdate } from '../model/systemMessageUpdate';

import { WC_API_BASE_PATH } from 'web-console-core';
import { Configuration }                                     from '../configuration';
import { SystemServiceInterface }                            from './system.serviceInterface';


@Injectable({
  providedIn: 'root'
})
export class SystemService implements SystemServiceInterface {

    protected basePath = 'http://localhost:8080/rest/v2';
    public defaultHeaders = new HttpHeaders();
    public configuration = new Configuration();

    constructor(protected httpClient: HttpClient, @Optional()@Inject(WC_API_BASE_PATH) basePath: string, @Optional() configuration: Configuration) {

        if (configuration) {
            this.configuration = configuration;
            this.configuration.basePath = configuration.basePath || basePath || this.basePath;

        } else {
            this.configuration.basePath = basePath || this.basePath;
        }
    }

    /**
     * @param consumes string[] mime-types
     * @return true: consumes contains 'multipart/form-data', false: otherwise
     */
    private canConsumeForm(consumes: string[]): boolean {
        const form = 'multipart/form-data';
        for (const consume of consumes) {
            if (form === consume) {
                return true;
            }
        }
        return false;
    }


    /**
     * Creates a system category
     * Creates a system category
     * @param domain Domain Name
     * @param systemCategoryCreate 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public createSystemCategory(domain: string, systemCategoryCreate?: SystemCategoryCreate, observe?: 'body', reportProgress?: boolean): Observable<SystemCategory>;
    public createSystemCategory(domain: string, systemCategoryCreate?: SystemCategoryCreate, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<SystemCategory>>;
    public createSystemCategory(domain: string, systemCategoryCreate?: SystemCategoryCreate, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<SystemCategory>>;
    public createSystemCategory(domain: string, systemCategoryCreate?: SystemCategoryCreate, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {
        if (domain === null || domain === undefined) {
            throw new Error('Required parameter domain was null or undefined when calling createSystemCategory.');
        }

        let headers = this.defaultHeaders;

        // authentication (vipera_basic) required
        if (this.configuration.username || this.configuration.password) {
            headers = headers.set('Authorization', 'Basic ' + btoa(this.configuration.username + ':' + this.configuration.password));
        }

        // authentication (vipera_cookie) required
        // authentication (vipera_oauth2) required
        if (this.configuration.accessToken) {
            const accessToken = typeof this.configuration.accessToken === 'function'
                ? this.configuration.accessToken()
                : this.configuration.accessToken;
            headers = headers.set('Authorization', 'Bearer ' + accessToken);
        }

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected !== undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected !== undefined) {
            headers = headers.set('Content-Type', httpContentTypeSelected);
        }

        return this.httpClient.post<SystemCategory>(`${this.configuration.basePath}/platform/domains/${encodeURIComponent(String(domain))}/system/categories`,
            systemCategoryCreate,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Creates a system message
     * Creates a system message
     * @param domain Domain Name
     * @param category System Category Name
     * @param systemMessageCreate 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public createSystemMessage(domain: string, category: string, systemMessageCreate?: SystemMessageCreate, observe?: 'body', reportProgress?: boolean): Observable<SystemMessage>;
    public createSystemMessage(domain: string, category: string, systemMessageCreate?: SystemMessageCreate, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<SystemMessage>>;
    public createSystemMessage(domain: string, category: string, systemMessageCreate?: SystemMessageCreate, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<SystemMessage>>;
    public createSystemMessage(domain: string, category: string, systemMessageCreate?: SystemMessageCreate, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {
        if (domain === null || domain === undefined) {
            throw new Error('Required parameter domain was null or undefined when calling createSystemMessage.');
        }
        if (category === null || category === undefined) {
            throw new Error('Required parameter category was null or undefined when calling createSystemMessage.');
        }

        let headers = this.defaultHeaders;

        // authentication (vipera_basic) required
        if (this.configuration.username || this.configuration.password) {
            headers = headers.set('Authorization', 'Basic ' + btoa(this.configuration.username + ':' + this.configuration.password));
        }

        // authentication (vipera_cookie) required
        // authentication (vipera_oauth2) required
        if (this.configuration.accessToken) {
            const accessToken = typeof this.configuration.accessToken === 'function'
                ? this.configuration.accessToken()
                : this.configuration.accessToken;
            headers = headers.set('Authorization', 'Bearer ' + accessToken);
        }

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected !== undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected !== undefined) {
            headers = headers.set('Content-Type', httpContentTypeSelected);
        }

        return this.httpClient.post<SystemMessage>(`${this.configuration.basePath}/platform/domains/${encodeURIComponent(String(domain))}/system/categories/${encodeURIComponent(String(category))}/messages`,
            systemMessageCreate,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Deletes a system category
     * Deletes a system category
     * @param domain Domain Name
     * @param category System Category Name
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public deleteSystemCategory(domain: string, category: string, observe?: 'body', reportProgress?: boolean): Observable<any>;
    public deleteSystemCategory(domain: string, category: string, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<any>>;
    public deleteSystemCategory(domain: string, category: string, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<any>>;
    public deleteSystemCategory(domain: string, category: string, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {
        if (domain === null || domain === undefined) {
            throw new Error('Required parameter domain was null or undefined when calling deleteSystemCategory.');
        }
        if (category === null || category === undefined) {
            throw new Error('Required parameter category was null or undefined when calling deleteSystemCategory.');
        }

        let headers = this.defaultHeaders;

        // authentication (vipera_basic) required
        if (this.configuration.username || this.configuration.password) {
            headers = headers.set('Authorization', 'Basic ' + btoa(this.configuration.username + ':' + this.configuration.password));
        }

        // authentication (vipera_cookie) required
        // authentication (vipera_oauth2) required
        if (this.configuration.accessToken) {
            const accessToken = typeof this.configuration.accessToken === 'function'
                ? this.configuration.accessToken()
                : this.configuration.accessToken;
            headers = headers.set('Authorization', 'Bearer ' + accessToken);
        }

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected !== undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.delete<any>(`${this.configuration.basePath}/platform/domains/${encodeURIComponent(String(domain))}/system/categories/${encodeURIComponent(String(category))}`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Deletes system message
     * Deletes system message
     * @param domain Domain Name
     * @param category System Category Name
     * @param locale Locale Name
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public deleteSystemMessage(domain: string, category: string, locale: string, observe?: 'body', reportProgress?: boolean): Observable<any>;
    public deleteSystemMessage(domain: string, category: string, locale: string, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<any>>;
    public deleteSystemMessage(domain: string, category: string, locale: string, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<any>>;
    public deleteSystemMessage(domain: string, category: string, locale: string, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {
        if (domain === null || domain === undefined) {
            throw new Error('Required parameter domain was null or undefined when calling deleteSystemMessage.');
        }
        if (category === null || category === undefined) {
            throw new Error('Required parameter category was null or undefined when calling deleteSystemMessage.');
        }
        if (locale === null || locale === undefined) {
            throw new Error('Required parameter locale was null or undefined when calling deleteSystemMessage.');
        }

        let headers = this.defaultHeaders;

        // authentication (vipera_basic) required
        if (this.configuration.username || this.configuration.password) {
            headers = headers.set('Authorization', 'Basic ' + btoa(this.configuration.username + ':' + this.configuration.password));
        }

        // authentication (vipera_cookie) required
        // authentication (vipera_oauth2) required
        if (this.configuration.accessToken) {
            const accessToken = typeof this.configuration.accessToken === 'function'
                ? this.configuration.accessToken()
                : this.configuration.accessToken;
            headers = headers.set('Authorization', 'Bearer ' + accessToken);
        }

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected !== undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.delete<any>(`${this.configuration.basePath}/platform/domains/${encodeURIComponent(String(domain))}/system/categories/${encodeURIComponent(String(category))}/messages/${encodeURIComponent(String(locale))}`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Retrieves system categories list
     * Retrieves system categories list
     * @param domain Domain Name
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getSystemCategories(domain: string, observe?: 'body', reportProgress?: boolean): Observable<Array<SystemCategory>>;
    public getSystemCategories(domain: string, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<Array<SystemCategory>>>;
    public getSystemCategories(domain: string, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<Array<SystemCategory>>>;
    public getSystemCategories(domain: string, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {
        if (domain === null || domain === undefined) {
            throw new Error('Required parameter domain was null or undefined when calling getSystemCategories.');
        }

        let headers = this.defaultHeaders;

        // authentication (vipera_basic) required
        if (this.configuration.username || this.configuration.password) {
            headers = headers.set('Authorization', 'Basic ' + btoa(this.configuration.username + ':' + this.configuration.password));
        }

        // authentication (vipera_cookie) required
        // authentication (vipera_oauth2) required
        if (this.configuration.accessToken) {
            const accessToken = typeof this.configuration.accessToken === 'function'
                ? this.configuration.accessToken()
                : this.configuration.accessToken;
            headers = headers.set('Authorization', 'Bearer ' + accessToken);
        }

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected !== undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.get<Array<SystemCategory>>(`${this.configuration.basePath}/platform/domains/${encodeURIComponent(String(domain))}/system/categories`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Retrieves a system category
     * Retrieves a system category
     * @param domain Domain Name
     * @param category System Category Name
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getSystemCategory(domain: string, category: string, observe?: 'body', reportProgress?: boolean): Observable<SystemCategory>;
    public getSystemCategory(domain: string, category: string, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<SystemCategory>>;
    public getSystemCategory(domain: string, category: string, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<SystemCategory>>;
    public getSystemCategory(domain: string, category: string, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {
        if (domain === null || domain === undefined) {
            throw new Error('Required parameter domain was null or undefined when calling getSystemCategory.');
        }
        if (category === null || category === undefined) {
            throw new Error('Required parameter category was null or undefined when calling getSystemCategory.');
        }

        let headers = this.defaultHeaders;

        // authentication (vipera_basic) required
        if (this.configuration.username || this.configuration.password) {
            headers = headers.set('Authorization', 'Basic ' + btoa(this.configuration.username + ':' + this.configuration.password));
        }

        // authentication (vipera_cookie) required
        // authentication (vipera_oauth2) required
        if (this.configuration.accessToken) {
            const accessToken = typeof this.configuration.accessToken === 'function'
                ? this.configuration.accessToken()
                : this.configuration.accessToken;
            headers = headers.set('Authorization', 'Bearer ' + accessToken);
        }

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected !== undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.get<SystemCategory>(`${this.configuration.basePath}/platform/domains/${encodeURIComponent(String(domain))}/system/categories/${encodeURIComponent(String(category))}`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Retrieves system message
     * Retrieves system message
     * @param domain Domain Name
     * @param category System Category Name
     * @param locale Locale Name
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getSystemMessage(domain: string, category: string, locale: string, observe?: 'body', reportProgress?: boolean): Observable<Array<SystemMessage>>;
    public getSystemMessage(domain: string, category: string, locale: string, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<Array<SystemMessage>>>;
    public getSystemMessage(domain: string, category: string, locale: string, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<Array<SystemMessage>>>;
    public getSystemMessage(domain: string, category: string, locale: string, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {
        if (domain === null || domain === undefined) {
            throw new Error('Required parameter domain was null or undefined when calling getSystemMessage.');
        }
        if (category === null || category === undefined) {
            throw new Error('Required parameter category was null or undefined when calling getSystemMessage.');
        }
        if (locale === null || locale === undefined) {
            throw new Error('Required parameter locale was null or undefined when calling getSystemMessage.');
        }

        let headers = this.defaultHeaders;

        // authentication (vipera_basic) required
        if (this.configuration.username || this.configuration.password) {
            headers = headers.set('Authorization', 'Basic ' + btoa(this.configuration.username + ':' + this.configuration.password));
        }

        // authentication (vipera_cookie) required
        // authentication (vipera_oauth2) required
        if (this.configuration.accessToken) {
            const accessToken = typeof this.configuration.accessToken === 'function'
                ? this.configuration.accessToken()
                : this.configuration.accessToken;
            headers = headers.set('Authorization', 'Bearer ' + accessToken);
        }

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected !== undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.get<Array<SystemMessage>>(`${this.configuration.basePath}/platform/domains/${encodeURIComponent(String(domain))}/system/categories/${encodeURIComponent(String(category))}/messages/${encodeURIComponent(String(locale))}`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Retrieves system messages
     * Retrieves system messages
     * @param domain Domain Name
     * @param category System Category Name
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getSystemMessages(domain: string, category: string, observe?: 'body', reportProgress?: boolean): Observable<Array<SystemMessage>>;
    public getSystemMessages(domain: string, category: string, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<Array<SystemMessage>>>;
    public getSystemMessages(domain: string, category: string, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<Array<SystemMessage>>>;
    public getSystemMessages(domain: string, category: string, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {
        if (domain === null || domain === undefined) {
            throw new Error('Required parameter domain was null or undefined when calling getSystemMessages.');
        }
        if (category === null || category === undefined) {
            throw new Error('Required parameter category was null or undefined when calling getSystemMessages.');
        }

        let headers = this.defaultHeaders;

        // authentication (vipera_basic) required
        if (this.configuration.username || this.configuration.password) {
            headers = headers.set('Authorization', 'Basic ' + btoa(this.configuration.username + ':' + this.configuration.password));
        }

        // authentication (vipera_cookie) required
        // authentication (vipera_oauth2) required
        if (this.configuration.accessToken) {
            const accessToken = typeof this.configuration.accessToken === 'function'
                ? this.configuration.accessToken()
                : this.configuration.accessToken;
            headers = headers.set('Authorization', 'Bearer ' + accessToken);
        }

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected !== undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.get<Array<SystemMessage>>(`${this.configuration.basePath}/platform/domains/${encodeURIComponent(String(domain))}/system/categories/${encodeURIComponent(String(category))}/messages`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Updates a system message
     * Updates a system message
     * @param domain Domain Name
     * @param category System Category Name
     * @param locale Locale Name
     * @param systemMessageUpdate 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public updateSystemMessage(domain: string, category: string, locale: string, systemMessageUpdate?: SystemMessageUpdate, observe?: 'body', reportProgress?: boolean): Observable<any>;
    public updateSystemMessage(domain: string, category: string, locale: string, systemMessageUpdate?: SystemMessageUpdate, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<any>>;
    public updateSystemMessage(domain: string, category: string, locale: string, systemMessageUpdate?: SystemMessageUpdate, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<any>>;
    public updateSystemMessage(domain: string, category: string, locale: string, systemMessageUpdate?: SystemMessageUpdate, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {
        if (domain === null || domain === undefined) {
            throw new Error('Required parameter domain was null or undefined when calling updateSystemMessage.');
        }
        if (category === null || category === undefined) {
            throw new Error('Required parameter category was null or undefined when calling updateSystemMessage.');
        }
        if (locale === null || locale === undefined) {
            throw new Error('Required parameter locale was null or undefined when calling updateSystemMessage.');
        }

        let headers = this.defaultHeaders;

        // authentication (vipera_basic) required
        if (this.configuration.username || this.configuration.password) {
            headers = headers.set('Authorization', 'Basic ' + btoa(this.configuration.username + ':' + this.configuration.password));
        }

        // authentication (vipera_cookie) required
        // authentication (vipera_oauth2) required
        if (this.configuration.accessToken) {
            const accessToken = typeof this.configuration.accessToken === 'function'
                ? this.configuration.accessToken()
                : this.configuration.accessToken;
            headers = headers.set('Authorization', 'Bearer ' + accessToken);
        }

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected !== undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected !== undefined) {
            headers = headers.set('Content-Type', httpContentTypeSelected);
        }

        return this.httpClient.put<any>(`${this.configuration.basePath}/platform/domains/${encodeURIComponent(String(domain))}/system/categories/${encodeURIComponent(String(category))}/messages/${encodeURIComponent(String(locale))}`,
            systemMessageUpdate,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

}
