/**
 * Motif Platform Service API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 2.0.0
 * Contact: info@vipera.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { ErrorVipera } from '../model/errorVipera';
import { SystemCategoriesList } from '../model/systemCategoriesList';
import { SystemCategory } from '../model/systemCategory';
import { SystemCategoryCreate } from '../model/systemCategoryCreate';
import { SystemCategoryData } from '../model/systemCategoryData';
import { SystemMessage } from '../model/systemMessage';
import { SystemMessageCreate } from '../model/systemMessageCreate';
import { SystemMessageUpdate } from '../model/systemMessageUpdate';
import { SystemMessagesList } from '../model/systemMessagesList';


import { Configuration }                                     from '../configuration';


export interface SystemServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;
    

    /**
    * Creates a system category
    * Creates a system category
    * @param domain Domain Name
    * @param systemCategoryCreate 
    */
    createSystemCategory(domain: string, systemCategoryCreate?: SystemCategoryCreate, extraHttpRequestParams?: any): Observable<SystemCategory>;

    /**
    * Creates a system message
    * Creates a system message
    * @param domain Domain Name
    * @param category System Category Name
    * @param systemMessageCreate 
    */
    createSystemMessage(domain: string, category: string, systemMessageCreate?: SystemMessageCreate, extraHttpRequestParams?: any): Observable<SystemMessage>;

    /**
    * Deletes a system category
    * Deletes a system category
    * @param domain Domain Name
    * @param category System Category Name
    */
    deleteSystemCategory(domain: string, category: string, extraHttpRequestParams?: any): Observable<any>;

    /**
    * Deletes system message
    * Deletes system message
    * @param domain Domain Name
    * @param category System Category Name
    * @param locale Locale Name
    */
    deleteSystemMessage(domain: string, category: string, locale: string, extraHttpRequestParams?: any): Observable<any>;

    /**
    * Retrieves system categories list
    * Retrieves system categories list
    * @param domain Domain Name
    */
    getSystemCategories(domain: string, extraHttpRequestParams?: any): Observable<SystemCategoriesList>;

    /**
    * Retrieves a system category
    * Retrieves a system category
    * @param domain Domain Name
    * @param category System Category Name
    */
    getSystemCategory(domain: string, category: string, extraHttpRequestParams?: any): Observable<SystemCategory>;

    /**
    * Retrieves system message
    * Retrieves system message
    * @param domain Domain Name
    * @param category System Category Name
    * @param locale Locale Name
    */
    getSystemMessage(domain: string, category: string, locale: string, extraHttpRequestParams?: any): Observable<SystemMessagesList>;

    /**
    * Retrieves system messages
    * Retrieves system messages
    * @param domain Domain Name
    * @param category System Category Name
    */
    getSystemMessages(domain: string, category: string, extraHttpRequestParams?: any): Observable<SystemMessagesList>;

    /**
    * Updates a system message
    * Updates a system message
    * @param domain Domain Name
    * @param category System Category Name
    * @param locale Locale Name
    * @param systemMessageUpdate 
    */
    updateSystemMessage(domain: string, category: string, locale: string, systemMessageUpdate?: SystemMessageUpdate, extraHttpRequestParams?: any): Observable<any>;

}
