/**
 * Motif App Content Service API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2.0.0
 * Contact: info@vipera.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface AppCheckRequest { 
    /**
     * Engine version
     */
    engineVer: string;
    /**
     * Asset bundle name
     */
    asset: string;
    /**
     * Asset bundle version
     */
    assetVer?: string;
    /**
     * User ID of requestor
     */
    userId?: string;
    /**
     * Application Name
     */
    app?: string;
    /**
     * Vipera-Serial generated by mobile app
     */
    viperaSerial?: string;
    /**
     * Device model
     */
    devModel?: string;
}