/**
 * Motif Service Catalog API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 2.0.0
 * Contact: info@vipera.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { ErrorVipera } from '../model/errorVipera';
import { Property } from '../model/property';
import { Service } from '../model/service';


import { Configuration }                                     from '../configuration';


export interface ApplicationsServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;
    

    /**
    * Gets application property value
    * Gets application property value
    * @param domain Domain Name
    * @param application Application Name
    * @param property Property
    */
    getApplicationProperty(domain: string, application: string, property: string, extraHttpRequestParams?: any): Observable<Property>;

    /**
    * Collects all service infos that belong to an application
    * Collects all service infos that belong to an application
    * @param domain Domain Name
    * @param application Application Name
    */
    getServiceList(domain: string, application: string, extraHttpRequestParams?: any): Observable<Array<Service>>;

}
